<template>
  <div>
    <h4>HTML/CSS</h4>
    <ul>
      <li>
        <NuxtLink
          to="/htmlcss/BasicKnowledgeOfHtml"
        >
          HTMLの基礎知識
        </NuxtLink>
      </li>
      <li>
        <NuxtLink
          to="/htmlcss/AllElements"
        >
          HTML 全要素
        </NuxtLink>
      </li>
      <li>
        <NuxtLink
          to="/htmlcss/GlobalAttributes"
        >
          グローバル属性
        </NuxtLink>
      </li>
      <li>
        <NuxtLink
          to="/htmlcss/OverallStructureAndMetainformation"
        >
          全体構造とメタ情報
        </NuxtLink>
      </li>
      <li>
        <NuxtLink
          to="/htmlcss/SectionAndBasicStructure"
        >
          セクションと基本構造
        </NuxtLink>
      </li>
      <li>
        <NuxtLink
          to="/htmlcss/TextElements"
        >
          テキスト関連の要素
        </NuxtLink>
      </li>
      <li>
        <NuxtLink
          to="/htmlcss/ListElements"
        >
          リスト関連の要素
        </NuxtLink>
      </li>
      <li>
        <NuxtLink
          to="/htmlcss/RubyElements"
        >
          ルビ関連の要素
        </NuxtLink>
      </li>
      <li>
        <NuxtLink
          to="/htmlcss/MediaElements"
        >
          画像・動画・音声関連の要素
        </NuxtLink>
      </li>
      <li>
        <NuxtLink
          to="/htmlcss/FormElements"
        >
          フォーム関連の要素
        </NuxtLink>
      </li>
      <li>
        <NuxtLink
          to="/htmlcss/TableElements"
        >
          テーブル関連の要素
        </NuxtLink>
      </li>
      <li>
        <NuxtLink
          to="/htmlcss/OtherElements"
        >
          その他の要素
        </NuxtLink>
      </li>
      <!-- CSS -->
      <li>
        <NuxtLink
          to="/htmlcss/BasicKnowledgeOfCss"
        >
          CSSの基礎知識
        </NuxtLink>
      </li>
      <li>
        <NuxtLink
          to="/htmlcss/CssSelector"
        >
          CSS セレクタ
        </NuxtLink>
      </li>
      <li>
        <NuxtLink
          to="/htmlcss/CSSPriority"
        >
          CSS適用の優先順位
        </NuxtLink>
      </li>
      <li>
        <NuxtLink
          to="/htmlcss/CSSColor"
        >
          CSS 色
        </NuxtLink>
      </li>
      <li>
        <NuxtLink
          to="/htmlcss/CSSBackground"
        >
          CSS 背景
        </NuxtLink>
      </li>
      <li>
        <NuxtLink
          to="/htmlcss/CSSText"
        >
          CSS テキスト
        </NuxtLink>
      </li>
      <li>
        <NuxtLink
          to="/htmlcss/CSSFont"
        >
          CSS フォント
        </NuxtLink>
      </li>
      <li>
        <NuxtLink
          to="/htmlcss/CSSBox"
        >
          CSS ボックス
        </NuxtLink>
      </li>
      <li>
        <NuxtLink
          to="/htmlcss/CSSAnimation"
        >
          CSS アニメーション
        </NuxtLink>
      </li>
      <li>
        <NuxtLink
          to="/htmlcss/CSSOther"
        >
          CSS その他
        </NuxtLink>
      </li>
    </ul>
  </div>
</template>

<script>
export default {
}
</script>

<style>
</style>
