<template>
  <div>
    <h4>HTML/CSS</h4>
    <ul>
      <li>
        <NuxtLink
          to="/htmlcss/SectionAndBasicStructure"
        >
          セクションと基本構造
        </NuxtLink>
      </li>
      <li>
        <NuxtLink
          to="/htmlcss/TextElements"
        >
          テキスト関連の要素
        </NuxtLink>
      </li>
      <li>
        <NuxtLink
          to="/htmlcss/ListElements"
        >
          リスト関連の要素
        </NuxtLink>
      </li>
      <li>
        <NuxtLink
          to="/htmlcss/RubyElements"
        >
          ルビ関連の要素
        </NuxtLink>
      </li>
      <li>
        <NuxtLink
          to="/htmlcss/MediaElements"
        >
          画像・動画・音声関連の要素
        </NuxtLink>
      </li>
      <li>
        <NuxtLink
          to="/htmlcss/FormElements"
        >
          フォーム関連の要素
        </NuxtLink>
      </li>
      <li>
        <NuxtLink
          to="/htmlcss/TableElements"
        >
          テーブル関連の要素
        </NuxtLink>
      </li>
      <li>
        <NuxtLink
          to="/htmlcss/OtherElements"
        >
          その他の要素
        </NuxtLink>
      </li>
    </ul>
  </div>
</template>

<script>
export default {
}
</script>

<style>
</style>
