<template>
  <div>
    <h4>サンプル</h4>
    <ul>
      <li>
        <NuxtLink
          to="/sample/SampleMustache"
        >
          マスタッシュ構文 {{}}
        </NuxtLink>
      </li>
      <li>
        <NuxtLink
          to="/sample/SampleVif"
        >
          v-if
        </NuxtLink>
      </li>
      <li>
        <NuxtLink
          to="/sample/SampleVfor"
        >
          v-for
        </NuxtLink>
      </li>
      <li>
        <NuxtLink
          to="/sample/SampleVbind"
        >
          v-bind（省略形 :）
        </NuxtLink>
      </li>
      <li>
        <NuxtLink
          to="/sample/SampleVbindClass"
        >
          v-bind:class（省略形 :class）
        </NuxtLink>
      </li>
      <li>
        <NuxtLink
          to="/sample/SampleVbindStyle"
        >
          v-bind:style（省略形 :style）
        </NuxtLink>
      </li>
      <li>
        <NuxtLink
          to="/sample/SampleVon"
        >
          v-on（省略形 @）
        </NuxtLink>
      </li>
      <li>
        <NuxtLink
          to="/sample/SampleVmodel"
        >
          v-model
        </NuxtLink>
      </li>
      <li>
        <NuxtLink
          to="/sample/SampleComputed"
        >
          算出プロパティ
        </NuxtLink>
      </li>
      <li>
        <NuxtLink
          to="/sample/SampleCssTransition"
        >
          CSSトランジション
        </NuxtLink>
      </li>
      <li>
        <NuxtLink
          to="/sample/SampleCssAnimation"
        >
          CSSアニメーション
        </NuxtLink>
      </li>
      <li>
        <NuxtLink
          to="/sample/SampleTransitionClass"
        >
          トランジションクラス
        </NuxtLink>
      </li>
      <li>
        <NuxtLink
          to="/sample/SampleListEnteringLeavingTransition"
        >
          リスト Entering/Leaving トランジション
        </NuxtLink>
      </li>
      <li>
        調査中
        <ul>
          <li>
            <NuxtLink
              to="/sample/SampleLifecycleHooks"
            >
              ライフサイクルフック
            </NuxtLink>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</template>

<script>
export default {
}
</script>

<style>
</style>
